#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
#
#############################################################################

# source & header files in this project (main.cpp is automatically assumed)

HEADERS += Beep.hpp
HEADERS += FireButton.hpp
HEADERS += Game_Parameter_Control.hpp
HEADERS += Hit_Run_Control.hpp
HEADERS += Hit_Transfer_Control.hpp
HEADERS += Init_Game_Control.hpp
HEADERS += IR_Receiver.hpp
HEADERS += IR_Sender.hpp
HEADERS += Keypad.hpp
HEADERS += Oled_Display.hpp
HEADERS += Receive_IR_Listener.hpp
HEADERS += Receive_IR_Message_Control.hpp
HEADERS += ScoreEntity.hpp
HEADERS += Send_IR_Message_Control.hpp
HEADERS += Shoot_Run_Control.hpp
HEADERS += Speaker.hpp
HEADERS += Time_Run_Control.hpp

#HEADERS += transmission.hpp
# other places to look for files for this project
SEARCH  :=

# set REATIVE to the next higher directory
# and defer to the Makefile.due there
RELATIVE := $(RELATIVE)../
include $(RELATIVE)Makefile.due
